services:
  rpi-dht-mqtt:
    image: rpi-dht-mqtt:latest
    build:
      context: ./
      dockerfile: Dockerfile
    privileged: true
    container_name: rpi-dht-mqtt
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - READ_TIME=${READ_TIME:-5}
      - DHT_PIN=${DHT_PIN:-17}
      - DHT_TYPE=${DHT_TYPE:-DHT22}
      - MQTT_BROKER=${MQTT_BROKER:-localhost}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_TOPIC=${MQTT_TOPIC:-/devices/rpi-casa}
      - MQTT_CLIENT_ID=${MQTT_CLIENT_ID:-rpi-user1}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    network_mode: host
    restart: unless-stopped
